version: '3'

services:
  db:
    image: library/postgres:12.6-alpine
    restart: always
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vinilcommerce